
install:
	cd common; make install
	cd cxxctn; make install
	cd hl7; make install
	cd domain; make install
	cd sr; make install
	cd meval; make install
	cd syslog; make install
	cd translators; make install

install_secure:
	cd syslog; make install_secure

clean:
	cd common; make clean
	cd cxxctn; make clean
	cd domain; make clean
	cd hl7; make clean
	cd meval; make clean
	cd sr; make clean
	cd syslog; make clean
	cd translators; make clean

headerexport:
	cd common; make headerexport
	cd cxxctn; make headerexport
	cd domain; make headerexport
	cd hl7; make headerexport
	cd meval; make headerexport
	cd sr; make headerexport
	cd syslog; make headerexport
	cd translators; make headerexport

doc-install:
	cd common; make doc-install
	cd cxxctn; make doc-install
	cd domain; make doc-install
	cd hl7; make doc-install
	cd meval; make doc-install
	cd sr; make doc-install
	cd syslog; make doc-install
	cd translators; make doc-install
