install:
	../../ctn/apps/scripts/createdirectory $(MESA_TARGET)/runtime
	cp msgRules.dss $(MESA_TARGET)/runtime
	cp segDefs.dss $(MESA_TARGET)/runtime
	cp msgRules.ihe $(MESA_TARGET)/runtime
	cp segDefs.ihe $(MESA_TARGET)/runtime
	cp msgRules.ihe-iti $(MESA_TARGET)/runtime
	cp segDefs.ihe-iti $(MESA_TARGET)/runtime
	cp msgRules.ordplc $(MESA_TARGET)/runtime
	cp segDefs.ordplc $(MESA_TARGET)/runtime
	cp syslogd* $(MESA_TARGET)/runtime
	cp version.txt $(MESA_TARGET)/runtime
	cp IHE-syslog-audit-message-4.xsd $(MESA_TARGET)/runtime
	cp IHE-ATNA-syslog-audit-message.xsd $(MESA_TARGET)/runtime
	cp xmldsig-core-schema.xsd $(MESA_TARGET)/runtime
	cp MESA-ATNA.xsl $(MESA_TARGET)/runtime
	cp -rpf expmgr $(MESA_TARGET)/runtime
	cp -rpf exprcr $(MESA_TARGET)/runtime
	cp -rpf imgmgr $(MESA_TARGET)/runtime
	cp -rpf imgmgr_study $(MESA_TARGET)/runtime
	cp -rpf rpt_manager $(MESA_TARGET)/runtime
	cp -rpf rpt_repos $(MESA_TARGET)/runtime
	cp -rpf wkstation $(MESA_TARGET)/runtime
	cp -rpf codes $(MESA_TARGET)/runtime
	cp -rpf certificates $(MESA_TARGET)/runtime
	cp -rpf certs-ca-signed $(MESA_TARGET)/runtime
	cp -rpf ldap $(MESA_TARGET)/runtime
#	cp -rpf connectathon $(MESA_TARGET)/runtime
