events:
	tpl_to_txt.pl ../vardb/a04a001.var ../templates/a04001.tpl a04b001.txt
	txt_to_hl7 < a04b001.txt > a04b001.hl7

	tpl_to_txt.pl ../vardb/orma001.var ../templates/orm001.tpl orma001.txt
	txt_to_hl7 < orma001.txt > orma001.hl7

	tpl_to_txt.pl ../vardb/orma002.var ../templates/orm002.tpl orma002.txt
	txt_to_hl7 < orma002.txt > orma002.hl7
