#!/usr/local/bin/perl -w

# Runs the Image Manager exam interactively.

use Env;
use lib "scripts";
require imgmgr;

$SIG{INT} = \&goodbye;


sub goodbye () {
  print "Exiting...\n";

  exit 1;
}

sub send_CFIND_X102_3DRECON {
  if ($MESA_OS eq "WINDOWS_NT") {
    $resultsDir = "1422\\gpsps_x102";
#    $resultsDirMESA = "1422\\gpsps_x102_mesa";
  } else {
    $resultsDir = "1422/gpsps_x102";
#    $resultsDirMESA = "1422/gpsps_x102_mesa";
  }

  mesa::delete_directory(1,$resultsDir);
#  mesa::delete_directory(1,$resultsDirMESA);

  mesa::create_directory($resultsDir);
#  mesa::create_directory($resultsDirMESA);

#  $x = "$MESA_TARGET/bin/dcm_create_object " .
#       " -i ../../msgs/ppm/142x/gpspsquery_delaware.txt" .
#       " ../../msgs/ppm/142x/gpspsquery_delaware.dcm";
#  if( $MESA_OS eq "WINDOWS_NT") {
#     $x =~ s(/)(\\)g;
#  }
#  print "$x\n";
#  # print `$x`;
#  `$x`;

  $x = "$MESA_TARGET/bin/cfind -a MODALITY1 -c $test_ppmAE" .
       " -f ../../msgs/ppm/142x/gpspsquery_delaware.dcm -o $resultsDir" .
       " -x GPWL $test_ppmHost $test_ppmPort";
  if( $MESA_OS eq "WINDOWS_NT") {
     $x =~ s(/)(\\)g;
  }
   print "$x\n";
   print `$x`;

#  $x = "$MESA_TARGET/bin/cfind -a MODALITY1 " .
#       " -f ../../msgs/ppm/142x/gpspsquery_delaware.dcm -o $resultsDirMESA" .
#       " -x GPWL $mesa_ppmHost $mesa_ppmPort";
#  if( $MESA_OS eq "WINDOWS_NT") {
#     $x =~ s(/)(\\)g;
#  }
#   print "$x\n";
#   print `$x`;

}

sub send_CFIND_again {
  if ($MESA_OS eq "WINDOWS_NT") {
    $resultsDir = "1422\\gpsps_x102_2";
  } else {
    $resultsDir = "1422/gpsps_x102_2";
  }

  mesa::delete_directory(1,$resultsDir);

  mesa::create_directory(1,$resultsDir);

  $x = "$MESA_TARGET/bin/cfind -a MODALITY1 -c $test_ppmAE" .
       " -f ../../msgs/ppm/142x/gpspsquery_delaware.dcm -o $resultsDir" .
       " -x GPWL $test_ppmHost $test_ppmPort";
  if( $MESA_OS eq "WINDOWS_NT") {
     $x =~ s(/)(\\)g;
  }
   print "$x\n";
   print `$x`;

}

sub send_release_claim {
  my $test_sopuid = shift(@_);
  my $resultsDir = shift(@_);

  if ($MESA_OS eq "WINDOWS_NT") {
    $outfile = "$resultsDir\\release_response.txt";
  } else {
    $outfile = "$resultsDir/release_response.txt";
  }

  open OUTPUT, ">$outfile" or die "could not open file $outfile";

#  $x = "$MESA_TARGET/bin/dcm_create_object " .
#       "-i ../../msgs/ppm/142x/spsrelease.txt" .
#       " ../../msgs/ppm/142x/spsrelease.dcm";
#  if( $MESA_OS eq "WINDOWS_NT") {
#     $x =~ s(/)(\\)g;
#  }
#  print "$x\n";
#  # print `$x`;
#  `$x`;

  $x = "$MESA_TARGET/bin/naction -a CT_3DRECON1 -c $test_ppmAE" .
       " $test_ppmHost $test_ppmPort GPSPS " .
       " ../../msgs/ppm/142x/spsrelease.dcm $test_sopuid";
  if( $MESA_OS eq "WINDOWS_NT") {
     $x =~ s(/)(\\)g;
  }
  print "$x\n";
  # print `$x`;
  print OUTPUT `$x`;

#  $x = "$MESA_TARGET/bin/naction -a CT_3DRECON1 " .
#       " $mesa_ppmHost $mesa_ppmPort GPSPS " .
#       " ../../msgs/ppm/142x/spsclaim.dcm $mesa_sopuid";
#  if( $MESA_OS eq "WINDOWS_NT") {
#     $x =~ s(/)(\\)g;
#  }
#   print "$x\n";
#   print `$x`;

  close OUTPUT;
}


# End of subroutines, beginning of the main code

#Setup commands
$host = `hostname`; chomp $host;


# ($mesaOFPortDICOM, $mesaOFPortHL7, $mesaImgMgrPortDICOM, $mesaImgMgrPortHL7,
#  $mesaModPortDICOM,
#  $mppsHost, $mppsPort, $mppsAE,
#  $imCStoreHost, $imCStorePort, $imCStoreAE,
#  $imCFindHost, $imCFindPort, $imCFindAE,
#  $imCommitHost, $imCommitPort, $imCommitAE,
#  $imHL7Host, $imHL7Port
# ) = imgmgr::read_config_params("imgmgr_test.cfg");

( $mesa_ppmHost, $mesa_ppmPort, $mesa_ppmAE,
  $test_ppmHost, $test_ppmPort, $test_ppmAE,
) = imgmgr::read_ppm_config_params("imgmgr_test.cfg");

# die "Illegal MESA Image Mgr HL7 Port: $mesaImgMgrPortHL7 \n" if ($mesaImgMgrPortHL7 == 0);


# announce test

print "\n" .
  "This is MESA Image Manager test 1422.  It tests post-processing\n" .
  "transactions for patient DELAWARE generated by script 142x.\n" .
  "This tests a post-processing manager's response to a request to\n" .
  "release a claim. It is assumed that this test is run immediately after\n" .
  "test 1421, so we should find a general purpose worklist for patient\n" .
  "DELAWARE with SPS workitem X102_3DRECON and status \"IN PROGRESS\"\n\n";

# Post-processing workstation queries test PPM for its worklist.

print "\n" .
  "The MESA CAD station will send a C-Find to query for its worklist.\n" .
  "The current workitem code is: X102_3DRECON \n" .
  "Press <enter> when ready to continue or <q> to quit: ";
$response = <STDIN>;
goodbye if ($response =~ /^q/);

send_CFIND_X102_3DRECON;

# $mesa_spsSOPUID = imgmgr::getSOPUID("1422/gpsps_x102_mesa/msg1_result.dcm");
# chomp $mesa_spsSOPUID;
# print "mesa_spsSOPUID: " . $mesa_spsSOPUID . "\n";

$test_spsSOPUID = imgmgr::getSOPUID("1422/gpsps_x102/msg1_result.dcm");
chomp $test_spsSOPUID;
print "test_spsSOPUID: " . $test_spsSOPUID . "\n";


# release claimed workitem.

print "\n" .
  "The MESA CAD station will send a GPSPS NACTION to release claim on the\n" .
  "workitem. \n" .
  "Press <enter> when ready to continue or <q> to quit: ";
$response = <STDIN>;
goodbye if ($response =~ /^q/);

if ($MESA_OS eq "WINDOWS_NT") {
  $claimResultsDir = "1422\\results";
} else {
  $claimResultsDir = "1422/results";
}

mesa::delete_directory(1,$claimResultsDir);
mesa::create_directory(1,$claimResultsDir);

send_release_claim($test_spsSOPUID, $claimResultsDir);

print "\n" .
  "The MESA CAD station will send a second C-Find to query for its worklist.\n" .
  "The status should be \"SCHEDULED\"\n" .
  "Press <enter> when ready to continue or <q> to quit: ";
$response = <STDIN>;
goodbye if ($response =~ /^q/);

send_CFIND_again;

print "\n" .
  "The Image Manager test 1422 is complete.  To evaluate \n" .
  "your responses:  \n" .
  "   perl 1422/eval_1422.pl [-v] \n";

goodbye;
