/*
		A basic implementation of the JDialog class.
*/

import java.awt.*;
import javax.swing.*;
import java.util.Vector;
import DICOM.*;

public class SimpleImageSection extends javax.swing.JDialog
{
    private java.util.Vector mParentContentItemVector;
	public SimpleImageSection(Frame parent)
	{
		super(parent);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(null);
		setSize(419,371);
		setVisible(false);
		JLabel1.setText("Section Heading");
		getContentPane().add(JLabel1);
		JLabel1.setBounds(24,24,110,28);
		getContentPane().add(sectionHeading);
		sectionHeading.setBounds(156,24,204,30);
		JLabel2.setText("Image Reference");
		getContentPane().add(JLabel2);
		JLabel2.setBounds(24,72,109,31);
		JLabel3.setText("Report Text");
		getContentPane().add(JLabel3);
		JLabel3.setBounds(24,168,105,23);
		getContentPane().add(ReportText);
		ReportText.setBounds(156,156,204,90);
		JLabel4.setText("Inferred From");
		getContentPane().add(JLabel4);
		JLabel4.setBounds(24,264,106,36);
		JButton1.setText("Complete");
		getContentPane().add(JButton1);
		JButton1.setBounds(96,312,90,27);
		JButton2.setText("Cancel");
		getContentPane().add(JButton2);
		JButton2.setBounds(228,312,90,27);
		JLabel5.setText("Text Type");
		getContentPane().add(JLabel5);
		JLabel5.setBounds(24,108,120,30);
		getContentPane().add(textType);
		textType.setBounds(156,108,201,26);
		//}}
	
		//{{REGISTER_LISTENERS
		SymMouse aSymMouse = new SymMouse();
		JButton1.addMouseListener(aSymMouse);
		SymAction lSymAction = new SymAction();
		JButton2.addActionListener(lSymAction);
		JButton1.addActionListener(lSymAction);
		//}}
	}

	public SimpleImageSection()
	{
		this((Frame)null);
	}

	public SimpleImageSection(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new SimpleImageSection()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	javax.swing.JComboBox sectionHeading = new javax.swing.JComboBox();
	javax.swing.JLabel JLabel2 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel3 = new javax.swing.JLabel();
	javax.swing.JTextArea ReportText = new javax.swing.JTextArea();
	javax.swing.JLabel JLabel4 = new javax.swing.JLabel();
	javax.swing.JButton JButton1 = new javax.swing.JButton();
	javax.swing.JButton JButton2 = new javax.swing.JButton();
	javax.swing.JLabel JLabel5 = new javax.swing.JLabel();
	javax.swing.JComboBox textType = new javax.swing.JComboBox();
	//}}
	
	public void loadSectionHeading() {
        DICOM.Code.CodeManager m = new DICOM.Code.CodeManager();
        java.util.Vector v = m.readCodeTable("sr/section_heading.txt");
        int i = 0;
        for (i = 0; i < v.size(); i++) {
            DICOM.Code.CodeItem item = (DICOM.Code.CodeItem)v.elementAt(i);
            sectionHeading.addItem(item.codeMeaning());
        }
        
        v = m.readCodeTable("sr/text_concept_name.txt");
        for (i = 0; i < v.size(); i++) {
            DICOM.Code.CodeItem item = (DICOM.Code.CodeItem)v.elementAt(i);
            textType.addItem(item.codeMeaning());
        }
	}
	public void setParentContentItemVector(java.util.Vector v) {
	    mParentContentItemVector = v;
	}
	public void sectionComplete() {
	    String sectionTitle = (String)sectionHeading.getSelectedItem();
	    if (sectionTitle == null)
	        return;
	    DICOM.Code.CodeManager mgr = new DICOM.Code.CodeManager();
	    DICOM.Code.CodeItem item = mgr.matchMeaning(sectionTitle, "sr/section_heading.txt");
	    if (item == null) {
	        return;
	    }
	    System.out.println("Section Heading: " + item.codeValue());
	    DICOM.SR.ContentItemFactory f = new DICOM.SR.ContentItemFactory();
	    DICOM.SR.ContentItem contentItem = f.produceContainer(item);
	    
	    String textTypeValue = (String)textType.getSelectedItem();
	    if (textTypeValue == null)
	        return;
	    DICOM.Code.CodeItem textCode =
	        mgr.matchMeaning(textTypeValue, "sr/text_concept_name.txt");
	        
	    String t = ReportText.getText();
	    DICOM.SR.ContentItem textContentItem =
	        f.produceText(textCode, "CONTAINS", t);
	    contentItem.addVectorItem(textContentItem);
	    
	    mParentContentItemVector.addElement(contentItem);
	    dispose();
	}
	public void sectionCancel() {
	}


	class SymMouse extends java.awt.event.MouseAdapter
	{
		public void mouseClicked(java.awt.event.MouseEvent event)
		{
			Object object = event.getSource();
			if (object == JButton1)
				JButton1_mouseClicked(event);
		}
	}

	void JButton1_mouseClicked(java.awt.event.MouseEvent event)
	{
		// to do: code goes here.
	}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButton2)
				JButton2_actionPerformed(event);
			else if (object == JButton1)
				JButton1_actionPerformed(event);
		}
	}

	void JButton2_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		JButton2_actionPerformed_Interaction1(event);
	}

	void JButton2_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			this.dispose();
		} catch (java.lang.Exception e) {
		}
	}

	void JButton1_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		JButton1_actionPerformed_Interaction1(event);
	}

	void JButton1_actionPerformed_Interaction1(java.awt.event.ActionEvent event)
	{
		try {
			this.sectionComplete();
		} catch (java.lang.Exception e) {
		}
	}
}