# Makefile for 

install:
	make CompositeEditor.class
	make CompositePainter.class
	make ContentItemNode.class
	make ContentItemNodeCODE.class
	make ContentItemNodeCONTAINER.class
	make ContentItemNodeFactory.class
	make ContentItemNodeIMAGE.class
	make ContentItemNodePNAME.class
	make ContentItemNodeTEXT.class
	make ContentItemNodeUIDREF.class

CompositeEditor.class: CompositeEditor.java
	$(JDK_ROOT)/bin/javac CompositeEditor.java

CompositePainter.class: CompositePainter.java
	$(JDK_ROOT)/bin/javac CompositePainter.java

ContentItemNode.class: ContentItemNode.java
	$(JDK_ROOT)/bin/javac ContentItemNode.java

ContentItemNodeCODE.class: ContentItemNodeCODE.java
	$(JDK_ROOT)/bin/javac ContentItemNodeCODE.java

ContentItemNodeCONTAINER.class: ContentItemNodeCONTAINER.java
	$(JDK_ROOT)/bin/javac ContentItemNodeCONTAINER.java

ContentItemNodeFactory.class: ContentItemNodeFactory.java
	$(JDK_ROOT)/bin/javac ContentItemNodeFactory.java

ContentItemNodeIMAGE.class: ContentItemNodeIMAGE.java
	$(JDK_ROOT)/bin/javac ContentItemNodeIMAGE.java

ContentItemNodePNAME.class: ContentItemNodePNAME.java
	$(JDK_ROOT)/bin/javac ContentItemNodePNAME.java

ContentItemNodeTEXT.class: ContentItemNodeTEXT.java
	$(JDK_ROOT)/bin/javac ContentItemNodeTEXT.java

ContentItemNodeUIDREF.class: ContentItemNodeUIDREF.java
	$(JDK_ROOT)/bin/javac ContentItemNodeUIDREF.java

clean:
	rm -f *.class *.o
