set M=D:\mesa\bin

copy ..\mesa_apps\archive_agent\debug\archive_agent.exe %M%
copy ..\mesa_apps\archive_cleaner\debug\archive_cleaner.exe %M%
copy ..\mesa_apps\archive_server\debug\archive_server.exe %M%
copy ..\mesa_apps\cfind\debug\cfind.exe %M%
copy ..\mesa_apps\cfind_study_probe\debug\cfind_study_probe.exe %M%
copy ..\mesa_apps\cmove\debug\cmove.exe %M%
copy ..\mesa_apps\cmove_study\debug\cmove_study.exe %M%
copy ..\mesa_apps\compare_dcm\debug\compare_dcm.exe %M%
copy ..\mesa_apps\compare_hl7\debug\compare_hl7.exe %M%
copy ..\mesa_apps\cstore\debug\cstore.exe %M%
copy ..\mesa_apps\ctn_version\debug\ctn_version.exe %M%
copy ..\mesa_apps\dcm_create_object\debug\dcm_create_object.exe %M%
copy ..\mesa_apps\dcm_ctnto10\debug\dcm_ctnto10.exe %M%
copy ..\mesa_apps\dcm_diff\debug\dcm_diff.exe %M%
copy ..\mesa_apps\dcm_dump_compressed\debug\dcm_dump_compressed.exe %M%
copy ..\mesa_apps\dcm_dump_element\debug\dcm_dump_element.exe %M%
copy ..\mesa_apps\dcm_dump_file\debug\dcm_dump_file.exe %M%
copy ..\mesa_apps\dcm_make_object\debug\dcm_make_object.exe %M%
copy ..\mesa_apps\dcm_map_to_8\debug\dcm_map_to_8.exe %M%
copy ..\mesa_apps\dcm_modify_elements\debug\dcm_modify_elements.exe %M%
copy ..\mesa_apps\dcm_modify_object\debug\dcm_modify_object.exe %M%
copy ..\mesa_apps\dcm_print_dictionary\debug\dcm_print_dictionary.exe %M%
copy ..\mesa_apps\dcm_print_element\debug\dcm_print_element.exe %M%
copy ..\mesa_apps\dcm_ref_sop_seq\debug\dcm_ref_sop_seq.exe %M%
copy ..\mesa_apps\dcm_replace_element\debug\dcm_replace_element.exe %M%
copy ..\mesa_apps\dcm_resize\debug\dcm_resize.exe %M%
copy ..\mesa_apps\dcm_rm_element\debug\dcm_rm_element.exe %M%
copy ..\mesa_apps\dcm_rm_group\debug\dcm_rm_group.exe %M%
copy ..\mesa_apps\dcm_to_html\debug\dcm_to_html.exe %M%
copy ..\mesa_apps\dcm_w_disp\debug\dcm_w_disp.exe %M%
copy ..\mesa_apps\dicom_echo\debug\dicom_echo.exe %M%
copy ..\mesa_apps\dump_commit_requests\debug\dump_commit_requests.exe %M%
copy ..\mesa_apps\hl7_get_value\debug\hl7_get_value.exe %M%
copy ..\mesa_apps\hl7_set_value\debug\hl7_set_value.exe %M%
copy ..\mesa_apps\hl7_to_txt\debug\hl7_to_txt.exe %M%
copy ..\mesa_apps\load_control\debug\load_control.exe %M%
copy ..\mesa_apps\mesa_dump_obj\debug\mesa_dump_obj.exe %M%
copy ..\mesa_apps\mwlquery\debug\mwlquery.exe %M%
copy ..\mesa_apps\naction\debug\naction.exe %M%
copy ..\mesa_apps\ncreate\debug\ncreate.exe %M%
copy ..\mesa_apps\nevent\debug\nevent.exe %M%
copy ..\mesa_apps\new_uids\debug\new_uids.exe %M%
copy ..\mesa_apps\nset\debug\nset.exe %M%
copy ..\mesa_apps\open_assoc\debug\open_assoc.exe %M%
copy ..\mesa_apps\sc_scp_association\debug\sc_scp_association.exe %M%
copy ..\mesa_apps\sc_scu_association\debug\sc_scu_association.exe %M%
copy ..\mesa_apps\send_hl7\debug\send_hl7.exe %M%
copy ..\mesa_apps\send_image\debug\send_image.exe %M%
copy ..\mesa_apps\simple_storage\debug\simple_storage.exe %M%
copy ..\mesa_apps\tcp_connect\debug\tcp_connect.exe %M%
copy ..\mesa_apps\ttdelete\debug\ttdelete.exe %M%
copy ..\mesa_apps\ttinsert\debug\ttinsert.exe %M%
copy ..\mesa_apps\ttlayout\debug\ttlayout.exe %M%
copy ..\mesa_apps\ttselect\debug\ttselect.exe %M%
copy ..\mesa_apps\ttunique\debug\ttunique.exe %M%
copy ..\mesa_apps\ttupdate\debug\ttupdate.exe %M%
copy ..\mesa_apps\txt_to_hl7\debug\txt_to_hl7.exe %M%
