apps:
	cd cecho;		make
	cd cfind;		make
	cd cfind_evaluate;	make
	cd cfind_image_avail;	make
	cd cfind_mwl_evaluate;	make
	cd cfind_gpsps_evaluate;	make
	cd cfind_resp_evaluate;	make
	cd cfind_study_probe;	make
	cd compare_dcm;		make
	cd compare_hl7;		make
	cd cmove;		make
	cd cstore;		make
	cd dcm_print_element;	make
	cd dcm_get_elements;	make
	cd ds_dcm;		make
	cd evaluate_storage_commit;	make
	cd evaluate_gppps;	make
	cd export_agent;	make
	cd hl7_evaluate;	make
	cd hl7_get_value;	make
	cd hl7_rcvr;		make
	cd hl7_set_value;	make
	cd hl7_to_txt;		make
	cd ihe_audit_message;	make
	cd im_dcmagent;		make
	cd im_dcmps;		make
#	cd im_hl7ps;		make
	cd kill_hl7;		make
	cd mesa_audit_eval;	make
	cd mesa_charset_xlate;	make
	cd mesa_composite_eval;	make
	cd mesa_db_test;	make
	cd mesa_dictionary;	make
	cd mesa_extract_nm_frames;	make
	cd mesa_dump_dicomdir;	make
	cd mesa_identifier;	make
	cd mesa_load_db;	make
	cd mesa_mwl_add_sps;	make
	cd mesa_mwl_sps_from_mpps;	make
	cd mesa_pdi_eval;	make
	cd mesa_schedule_mwl;	make
	cd mesa_select_column;	make
	cd mesa_sr_eval;	make
	cd mesa_strip_file;	make
	cd mesa_update_column;	make
#	cd mesa_xml_eval;	make
	cd mod_dcmps;		make
	cd mod_generatestudy;	make
#	cd mod_newuids;		make
	cd mod_weld_mwl;	make
	cd mpps_add_perf_series;make
	cd mpps_construct;	make
	cd mpps_evaluate;	make
	cd mpps_merge;		make
	cd mpps_ncreate;	make
	cd mwlquery;		make
	cd naction;		make
	cd ncreate;		make
	cd nevent;		make
	cd nset;		make
	cd of_cancel;		make
	cd of_dcmps;		make
#	cd of_hl7ps;		make
	cd of_identifier;	make
	cd of_mwl_cancel;	make
	cd of_schedule;		make
	cd of_sched_procedure;	make
#	cd op_hl7ps;		make
	cd of_new;		make
#	cd op_order;		make
#	cd op_send;		make
	cd open_assoc;		make
	cd pp_dcmps;		make
	cd ppm_sched_gppps;	make
	cd ppm_sched_gpsps;	make
	cd send_hl7;		make
	cd sc_scu_association;	make
	cd sc_scp_association;	make
	cd sr_to_hl7;		make
	cd syslog_client;	make
	cd syslog_extract;	make
	cd syslog_server;	make
	cd tcp_connect;		make
	cd txt_to_hl7;		make
#
#	cd HL7Client;	make
#	cd of_ps;	make
#	cd orderplacer;	make

install:
	cd cecho;		make install
	cd cfind;		make install
	cd cfind_evaluate;	make install
	cd cfind_image_avail;	make install
	cd cfind_mwl_evaluate;	make install
	cd cfind_gpsps_evaluate;	make install
	cd cfind_resp_evaluate;	make install
	cd cfind_study_probe;	make install
	cd compare_dcm;		make install
	cd compare_hl7;		make install
	cd cmove;		make install
	cd cstore;		make install
	cd dcm_print_element;	make install
	cd dcm_get_elements;	make install
	cd ds_dcm;		make install
	cd evaluate_storage_commit;	make install
	cd evaluate_gppps;	make install
	cd export_agent;	make install
	cd hl7_evaluate;	make install
	cd hl7_get_value;	make install
	cd hl7_rcvr;		make install
	cd hl7_set_value;	make install
	cd hl7_to_txt;		make install
	cd ihe_audit_message;	make install
	cd im_dcmagent;		make install
	cd im_dcmps;		make install
#	cd im_hl7ps;		make install
	cd kill_hl7;		make install
	cd mesa_audit_eval;	make install
	cd mesa_charset_xlate;	make install
	cd mesa_composite_eval;	make install
	cd mesa_db_test;	make install
	cd mesa_dictionary;	make install
	cd mesa_extract_nm_frames;	make install
	cd mesa_dump_dicomdir;	make install
	cd mesa_identifier;	make install
	cd mesa_load_db;	make install
	cd mesa_mwl_add_sps;	make install
	cd mesa_mwl_sps_from_mpps;	make install
	cd mesa_pdi_eval;	make install
	cd mesa_schedule_mwl;	make install
	cd mesa_select_column;	make install
	cd mesa_sr_eval;	make install
	cd mesa_strip_file;	make install
	cd mesa_update_column;	make install
#	cd mesa_xml_eval;	make install
	cd mod_dcmps;		make install
	cd mod_generatestudy;	make install
#	cd mod_newuids;		make install
	cd mod_weld_mwl;	make install
	cd mpps_add_perf_series;make install
	cd mpps_construct;	make install
	cd mpps_evaluate;	make install
	cd mpps_merge;		make install
	cd mpps_ncreate;	make install
	cd mwlquery;		make install
	cd naction;		make install
	cd ncreate;		make install
	cd nevent;		make install
	cd nset;		make install
	cd of_cancel;		make install
	cd of_dcmps;		make install
#	cd of_hl7ps;		make install
	cd of_identifier;	make install
	cd of_mwl_cancel;	make install
	cd of_schedule;		make install
	cd of_sched_procedure;	make install
#	cd op_hl7ps;		make install
	cd of_new;		make install
#	cd op_order;		make install
#	cd op_send;		make install
	cd open_assoc;		make install
	cd pp_dcmps;		make install
	cd ppm_sched_gppps;	make install
	cd ppm_sched_gpsps;	make install
	cd send_hl7;		make install
	cd sc_scu_association;	make install
	cd sc_scp_association;	make install
	cd sr_to_hl7;		make install
	cd syslog_client;	make install
	cd syslog_extract;	make install
	cd syslog_server;	make install
	cd tcp_connect;		make install
	cd txt_to_hl7;		make install
#
#	cd HL7Client;	make install
#	cd of_ps;	make install
#	cd orderplacer;	make install

install_secure:
	cd syslog_client;	make install_secure
	cd syslog_server;	make install_secure

clean:
	cd cecho;		make clean
	cd cfind;		make clean
	cd cfind_evaluate;	make clean
	cd cfind_image_avail;	make clean
	cd cfind_mwl_evaluate;	make clean
	cd cfind_gpsps_evaluate;	make clean
	cd cfind_resp_evaluate;	make clean
	cd cfind_study_probe;	make clean
	cd compare_dcm;		make clean
	cd compare_hl7;		make clean
	cd cmove;		make clean
	cd cstore;		make clean
	cd dcm_print_element;	make clean
	cd dcm_get_elements;	make clean
	cd ds_dcm;		make clean
	cd evaluate_storage_commit;	make clean
	cd evaluate_gppps;	make clean
	cd export_agent;	make clean
	cd hl7_evaluate;	make clean
	cd hl7_get_value;	make clean
	cd hl7_rcvr;		make clean
	cd hl7_set_value;	make clean
	cd hl7_to_txt;		make clean
	cd ihe_audit_message;	make clean
	cd im_dcmagent;		make clean
	cd im_dcmps;		make clean
#	cd im_hl7ps;		make clean
	cd kill_hl7;		make clean
	cd mesa_audit_eval;	make clean
	cd mesa_charset_xlate;	make clean
	cd mesa_composite_eval;	make clean
	cd mesa_db_test;	make clean
	cd mesa_dictionary;	make clean
	cd mesa_extract_nm_frames;	make clean
	cd mesa_dump_dicomdir;	make clean
	cd mesa_identifier;	make clean
	cd mesa_load_db;	make clean
	cd mesa_mwl_add_sps;	make clean
	cd mesa_mwl_sps_from_mpps;	make clean
	cd mesa_pdi_eval;	make clean
	cd mesa_schedule_mwl;	make clean
	cd mesa_select_column;	make clean
	cd mesa_sr_eval;	make clean
	cd mesa_strip_file;	make clean
	cd mesa_update_column;	make clean
	cd mesa_xml_eval;	make clean
	cd mod_dcmps;		make clean
	cd mod_generatestudy;	make clean
	cd mod_newuids;		make clean
	cd mod_weld_mwl;	make clean
	cd mpps_add_perf_series;make clean
	cd mpps_construct;	make clean
	cd mpps_evaluate;	make clean
	cd mpps_merge;		make clean
	cd mpps_ncreate;	make clean
	cd mwlquery;		make clean
	cd naction;		make clean
	cd ncreate;		make clean
	cd nevent;		make clean
	cd nset;		make clean
	cd of_cancel;		make clean
	cd of_dcmps;		make clean
#	cd of_hl7ps;		make clean
	cd of_identifier;	make clean
	cd of_mwl_cancel;	make clean
	cd of_schedule;		make clean
	cd of_sched_procedure;	make clean
#	cd op_hl7ps;		make clean
	cd of_new;		make clean
#	cd op_order;		make clean
#	cd op_send;		make clean
	cd open_assoc;		make clean
	cd pp_dcmps;		make clean
	cd ppm_sched_gppps;	make clean
	cd ppm_sched_gpsps;	make clean
	cd send_hl7;		make clean
	cd sc_scu_association;	make clean
	cd sc_scp_association;	make clean
	cd sr_to_hl7;		make clean
	cd syslog_client;	make clean
	cd syslog_extract;	make clean
	cd syslog_server;	make clean
	cd tcp_connect;		make clean
	cd txt_to_hl7;		make clean
#
#	cd HL7Client;	make clean
#	cd of_ps;	make clean
#	cd orderplacer;	make clean
