drop table ups;
create table ups (
  id            serial primary key,
  specharset	char(64),
  sopclauid	char(64),
  sopinsuid	char(64),
  spspri	char(16),
  spsmoddattim	char(20),
  prostelbl	text,
  worlbl	text,
  spsstadattim	char(20),
  expcomdattim	char(20),

  stuinsuid	char(64),
  nam		char(64),
  patid		char(20),
  issuer	char(100),
  datbir	char(8),
  sex		char(4),
  issueradmid	char(64),
  admdiagdes	text,

  upsstate	char(16),

	refstusopcla	char(64),
	refstusopins	char(64),
	reqproid	char(30),
	plaordnum	char(22),
	filordnum	char(22),
	accnum		char(20),
	quatim		char(20),
	everea		char(20),
	reqdattim	char(20),
	spesou		char(20),
	ordpro		char(20),
	reqprodes	char(64),
	reqprocod	char(30),
	occnum		char(20),
	apptimqua	char(30),
	orduid		char(20),
	spsid		char(16),
	spsindex	char(16),
	schaet		char(16),
	spsstadat	int,
	spsstatim	char(16),
	mod		char(16),
	schperphynam	char(64),
	spsdes		char(64),
	spsloc		char(16),
	premed		char(64),
	reqconage	char(64),
	schstanam	char(16),
	spssta		char(16),
	reqphynam	char(64),
	refphynam	char(64),
	patid2		char(20),
	issuer2		char(100),
	pataccnum	char(20),
	patrac		char(20),
	codmea		char(64),
	codval 		char(20),
	codschdes       char(20),
	pregstat	char(4),
	curpatloc	char(64),
	admid		char(64)
);

