install:
	cp web.xml $(TOMCAT_HOME)/webapps/ROOT/WEB-INF
	cp tomcat-users.xml $(TOMCAT_HOME)/conf
	cp blank.html $(TOMCAT_HOME)/webapps/ROOT
	cp ctn-control.html $(TOMCAT_HOME)/webapps/ROOT
	cp ctn.html $(TOMCAT_HOME)/webapps/ROOT
